### ISSUE TITLE
Hackage CI Matrix shows build failure for some ghc versions < 8.2

### ISSUE THREAD

**Issue by andreasabel** [skogsbaer/HTF#102]
Currently, https://matrix.hackage.haskell.org/#/package/HTF/ has `FAIL (pkg)` for ghc 7.6-8.0.
Since you only support ghc >= 8.2, the `base` constraint should be set to
```
base >= 4.10 && < 5
```
in order to switch the status to `OK (no-ip)`.

This can be done by a revision, not requiring a new release.

Note that @hvr did similar revisions to HTF-0.13, but they didn't end up in the repo, hence were lost.

**Comment by skogsbaer** [comment]
Thanks for pointing this out. But does this really matter? Who cares about GHC 8.0 and 7.*??

**Comment by andreasabel** [comment]
> Who cares about GHC 8.0 and 7.*??

Short answer: me. This makes it a non-empty set. Further, I am sure I am not the only one.
Medium answer: A Ubuntu LTS usually lives 5 years, so it might have a GHC older than 8.2.
Longer answer: Libraries are better to use if they impose less constraints on their use.

But supporting 8.0 and below was not my request.  It was about having the constraints reflect the status.

> But does this really matter?

The constraints in a cabal file are a contract.  If the constraints are satisfied, then the package
1. builds and
2. works as intended.

If a package is even _known_ not to build with configuration A, then configuration A should be ruled out by the constraints.

**Comment by skogsbaer** [comment]
fixed in 0.14.0.6

**Comment by andreasabel** [comment]
> Since you only support ghc >= 8.2, the `base` constraint should be set to
> 
> ```
> base >= 4.10 && < 5
> ```

Made this revision for 0.14.0.4/5 on hackage.
