### ISSUE TITLE
Error in VSCode + stack

### ISSUE THREAD

**Issue by chtenb** [skogsbaer/HTF#108]
When working in VSCode using the standard `Haskell` extension in a stack based project, VSCode complains about the following error:
![image](https://user-images.githubusercontent.com/1030961/117587635-41255400-b11f-11eb-8ba1-b8284bf4f302.png)

In text: `htfpp: runInteractiveProcess: runInteractiveProcess: exec: permission denied (Permission denied)`

When running `stack test` from the CLI it works fine.
I'm on WSL Ubuntu. Any clues as to what this error means and what angle I need to investigate?

**Comment by skogsbaer** [comment]
See https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html and
https://github.com/haskell/haskell-language-server/issues/176

Workaround: make sure that htfpp is in your $PATH
