### ISSUE TITLE
Older releases need revisions

### ISSUE THREAD

**Issue by Bodigrim** [skogsbaer/HTF#110]
Could you please make revisions for older releases, so that Hackage build matrix becomes green? Otherwise Cabal struggles to derive a working build plan.
https://matrix.hackage.haskell.org/#/package/HTF

**Comment by skogsbaer** [comment]
Which older versions do you want to use with which version of GHC? 

HTF Version 0.14.0.6 compiles with GHC 8.10, 8.8, 8.6, 8.4 and 8.2

**Comment by Bodigrim** [comment]
It's other way around: nothing prevents newer GHCs to pick up a prehistoric HTF and try compiling it, leading to build failures. As a Hackage trustee, I made necessary revisions, moving from https://matrix.hackage.haskell.org/#/package/HTF/0.14.0.6/ghc-8.10.1@1633529383 to https://matrix.hackage.haskell.org/#/package/HTF/0.14.0.6/ghc-8.10.1@1638478640.

**Comment by skogsbaer** [comment]
Thanks a lot!
