### ISSUE TITLE
Build failure with `mtl-2.3`

### ISSUE THREAD

**Issue by andreasabel** [skogsbaer/HTF#118]
`mtl-2.3` removed reexport of `Control.Monad`, so `when` isn't in scope by just importing `mtl` modules:
```
[20 of 24] Compiling Test.Framework.TestReporter ( Test/Framework/TestReporter.hs, dist/build/Test/Framework/TestReporter.o, dist/build/Test/Framework/TestReporter.dyn_o )

Test/Framework/TestReporter.hs:180:13: error: [GHC-88464]
    Variable not in scope: when :: Bool -> TR () -> m b
    |
180 |             when (tc_quiet tc) (reportHumanTestStartMessage Info ftr)
    |             ^^^^
```
PR:
- #117

I revised `HTF >= 0.11.1.0 && <= 0.15.0.0` on hackage with bound `mtl < 2.3`.

**Comment by andreasabel** [comment]
Maybe keep this open until #117 has been released.

**Comment by skogsbaer** [comment]
just release 0.15.0.1 to hackage: https://hackage.haskell.org/package/HTF-0.15.0.1
