### ISSUE TITLE
HTF does not build on Fedora 20 

### ISSUE THREAD

**Issue by ghost** [skogsbaer/HTF#38]
Hello, 

When I do cabal install HTF I see this output: 

In-place registering xmlgen-0.6.2.1...
Installing library in /root/.cabal/lib/xmlgen-0.6.2.1/ghc-7.6.3
Registering xmlgen-0.6.2.1...
Installed xmlgen-0.6.2.1
Downloading HTF-0.11.3.4...
Configuring HTF-0.11.3.4...
Building HTF-0.11.3.4...
Preprocessing library HTF-0.11.3.4...
ghc: could not execute: cpphs
Failed to install HTF-0.11.3.4
cabal: Error: some packages failed to install:
HTF-0.11.3.4 failed during the building phase. The exception was:
ExitFailure 1

cpphs is installed see this output: 
 cabal install cpphs
Resolving dependencies...
All the requested packages are already installed:
cpphs-1.18.4
Use --reinstall if you want to reinstall anyway.

Roelof

**Comment by skogsbaer** [comment]
Closing because of unresponsiveness.
