### ISSUE TITLE
htfpp can not handle ' type level operators

### ISSUE THREAD

**Issue by agrafix** [skogsbaer/HTF#48]
Consider this example:

    test_curryUncurry :: IO ()
    test_curryUncurry =
        do assertEqual "12" (fun (1 :&: 2 :&: empty))
           assertEqual "12" (HV.curry fun 1 2)
           assertEqual "12" (HV.uncurry (HV.curry fun) (1 :&: 2 :&: empty))
        where
          fun :: HVect '[Int, Int] -> String
          fun (a :&: b  :&: HNil) = show a ++ show b
          fun _ = "OOPS!"
    
    test_length :: IO ()
    test_length =
        do assertEqual 0 (sNatToInt $ HV.length empty)
           assertEqual 2 (sNatToInt $ HV.length ("foo" :&: "bar" :&: empty))

When compiling, I get a warning, that `test_length` is defined but never used. Probably the preprocessor aborts after `HVect '[Int, Int]`. Removing that everything works as expected.

**Comment by skogsbaer** [comment]
should be fixed in the newest version on hackage (0.13.0.0). Please reopen if the problem persists.
