### ISSUE TITLE
Test runs fail in GHCi under Windows

### ISSUE THREAD

**Issue by jh3141** [skogsbaer/HTF#60]
Running `htfMain mytests` under Windows in GHCi causes an exception:

```
*** Exception: .HTF/<interactive>.history: openBinaryFile: invalid argument (Invalid argument)
```

The cause is quite simple.  From Test/Framework/CmdlineOptions.hs:339:

```
  getHistoryFile =
      case opts_historyFile opts of
        Just fp -> return fp
        Nothing ->
            do x <- getProgName
               createDirectoryIfMissing False ".HTF"
               return (".HTF/" ++ x ++ ".history")
```

The issue is that under GHCi, `getProgName` returns the string `"<interactive>"`, but `<` and `>` are invalid characters for a filename under Windows.  I would suggest a simple filter to remove the set of invalid filename characters under Windows would be the best solution (see https://msdn.microsoft.com/en-gb/library/windows/desktop/aa365247(v=vs.85).aspx for a list).

**Comment by skogsbaer** [comment]
Now fixed in master.
