### ISSUE TITLE
suite fails because of history file

### ISSUE THREAD

**Issue by tek** [skogsbaer/HTF#75]
at the end of a test run, I get
```
proteome-unit: .HTF/proteome-unit.history: openBinaryFile: does not exist (No such file or directory)
```

causing the suite to fail.
project is https://github.com/tek/proteome-hs

the history file is present after the process ends.

**Comment by tek** [comment]
found out that this happened because of a `setWorkingDirectory` in one of the tests.
not sure this is a valid issue now, please close if you don't think so.

**Comment by skogsbaer** [comment]
Now fixed in master.
