### ISSUE TITLE
Publish HTF on stackage (ghc 8.8)

### ISSUE THREAD

**Issue by andreasabel** [skogsbaer/HTF#92]
It seems that HTF is not yet included in stackage for ghc 8.8: https://www.stackage.org/nightly-2019-12-07

**Comment by skogsbaer** [comment]
I'm trying to get it in again, but I'm now already waiting for one week just for the PR for haskell-src being merged: https://github.com/commercialhaskell/stackage/pull/5021

**Comment by skogsbaer** [comment]
There is now a PR: https://github.com/commercialhaskell/stackage/pull/5033

**Comment by skogsbaer** [comment]
The PR has been merged, so HTF should appear in stackage soon.

**Comment by andreasabel** [comment]
Thanks, I can build BNFC with stackage nightly 2019-12-30 now!
Happy new year!
