### ISSUE TITLE
Build failure on travis with cabal due to haskell-src

### ISSUE THREAD

**Issue by andreasabel** [skogsbaer/HTF#93]
I tried to use HTF with ghc 8.8 and cabal on travis, but it failed (see https://travis-ci.org/BNFC/bnfc/jobs/622005387 ):
```
trying: HTF-0.14.0.1 (dependency of bnfc-system-tests-0.1.1.0)
next goal: haskell-src (dependency of HTF-0.14.0.1)
rejecting: haskell-src-1.0.3.1 (unsupported spec-version 2.4)
```
According to https://matrix.hackage.haskell.org/#/package/haskell-src 1.0.3.1 is the only version to build with ghc 8.8, but there seems to be a conflict, as the hackage released version of haskell-src requires `cabal version: 2.4`.

So, maybe not the fault of HTF, but I anyway want to alert you of this problem.  See also my comment https://github.com/haskell-pkg-janitors/haskell-src/issues/8#issuecomment-562895012 .

**Comment by andreasabel** [comment]
I filed https://github.com/haskell-pkg-janitors/haskell-src/issues/10

**Comment by hvr** [comment]
> I filed [haskell-pkg-janitors/haskell-src#10](https://github.com/haskell-pkg-janitors/haskell-src/issues/10)

As pointed out there, the TLDR is that https://www.haskell.org/ghc/download_ghc_8_8_1.html clearly states that 

> ## Bundled packages and cabal-install
>
> **GHC 8.8 only works with cabal-install version 3.0 or later**. Please upgrade if you have an older version of cabal-install.

**Comment by skogsbaer** [comment]
Finally, haskell-src has made it into stackage, so HTF now compiles with GHC 8.10 (as well as 8.8, 8.6 and 8.4)
